services:
  # O coração do sistema: PHP + Swoole (Hyperf)
  app:
    image: hyperf/hyperf:latest
    container_name: hyperf_app
    volumes:
      - .:/data
    ports:
      - "9501:9501"
    environment:
      - SCAN_CACHEABLE=false
    networks:
      - hyperf_network
    tty: true
    stdin_open: true
    command: php /data/bin/hyperf.php start

  # Cassandra: Banco colunar para alta escala
  scylla:
    image: scylladb/scylla:latest
    container_name: hyperf_scylla
    command: --smp 1 --memory 2G --overprovisioned 1 --developer-mode 1
    ports:
      - "9042:9042"
    networks:
      - hyperf_network

  # Redis: Contador atômico e Cache
  redis:
    image: redis:alpine
    container_name: hyperf_redis
    ports:
      - "6379:6379"
    networks:
      - hyperf_network

networks:
  hyperf_network:
    driver: bridge