services:
  # O coração do sistema: PHP + Swoole (Hyperf)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hyperf_app
    volumes:
      # Mapeamento atualizado para o padrão do Dockerfile
      - ./:/opt/www
    ports:
      - "9501:9501"
    environment:
      - SCAN_CACHEABLE=false
    networks:
      - hyperf_network
    tty: true
    stdin_open: true
    command: php bin/hyperf.php start

  # PostgreSQL: O substituto de elite para o banco de dados
  postgres:
    image: postgres:16-alpine
    container_name: hyperf_postgres
    environment:
      POSTGRES_USER: hyperf
      POSTGRES_PASSWORD: root
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    networks:
      - hyperf_network

  # Redis: Contador atômico e Cache
  redis:
    image: redis:alpine
    container_name: hyperf_redis
    ports:
      - "6379:6379"
    networks:
      - hyperf_network

networks:
  hyperf_network:
    driver: bridge